replicaCount: 1

image:
  repository: hw05-gateway-user

service:
  type: NodePort
  port: 9000

externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"