apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressUserName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingressUserServiceName }}
                port:
                  number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressAuthName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.ingressAuthServiceName }}
                port:
                  number: 9000
            path: /auth/registration
            pathType: Prefix
          - backend:
              service:
                name: {{ .Values.ingressAuthServiceName }}
                port:
                  number: 9000
            path: /auth/login
            pathType: Prefix
          - backend:
              service:
                name: {{ .Values.ingressAuthServiceName }}
                port:
                  number: 9000
            path: /auth/auth
            pathType: Prefix
          - backend:
              service:
                name: {{ .Values.ingressAuthServiceName }}
                port:
                  number: 9000
            path: /auth/logout
            pathType: Prefix