apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  #GREETING: Bonjour
  #POSTGRES_SERVICE: localhost
  #POSTGRES_DB_PORT: "53120"
  #POSTGRES_DB_NAME: myapp
  #POSTGRES_DB_USER: myuser
  #POSTGRES_DB_PASSWORD: passwd
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://localhost:61384/myapp
    spring.datasource.username=myuser
    spring.datasource.password=passwd
