{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hw03-prometheus-chart.fullname" . }}
  labels:
    {{- include "hw03-prometheus-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "hw03-prometheus-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "hw03-prometheus-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: web
      path: /metrics
  {{- end }}
